
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.1.58-1-lts - x86_64
...
